### ISSUE TITLE
Only using one of the two callbacks here

### ISSUE THREAD

**Issue by shanemac10** [M-Schwiesow/teamroster#1]
https://github.com/M-Schwiesow/teamroster/blob/bf2bdb75cb5b34e0086841c45f6ce8d02b0e6690/server/controllers/players.js#L65

(err, response) => ect...

Not sure if this is THE issue you are having, but at least you will be getting amore info

**Comment by shanemac10** [comment]
https://github.com/Automattic/mongoose/issues/5022

**Comment by shanemac10** [comment]
@M-Schwiesow Are you getting these notifications?

**Comment by M-Schwiesow** [comment]
Apologies.  I was not getting those notifications.  The issue ended up being a failure to subscribe to the observable on delete methods in the team-roster component.
In this case, I don't have any plans to use the document removed, so the second callback isn't necessary.  Gonna go ahead and close this one out, and watch my issues more closely.
